import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { once } from 'node:events';
import { randomUUID } from 'node:crypto';
import { connect } from '../src/store.mjs';

test('worker HTTP validates methods and inputs, isolates owners and resumes prepared undo', {skip:!process.env.TEST_DATABASE_URL}, async()=>{
  const administration=await connect(process.env.TEST_DATABASE_URL);
  const schema=`backend_${randomUUID().replaceAll('-','')}`;
  await administration`CREATE SCHEMA ${administration(schema)}`;
  const database=new URL(process.env.TEST_DATABASE_URL);
  database.searchParams.set('options',`-c search_path=${schema}`);
  const sql=await connect(database.toString()), owner=randomUUID(), other=randomUUID(), asset=randomUUID(), change=randomUUID();
  let description='after', visibility='timeline';
  const mock=createServer((req,res)=>{res.setHeader('content-type','application/json');res.end(JSON.stringify({id:asset,ownerId:owner,visibility,exifInfo:{description}}));});
  mock.listen(0,'127.0.0.1');await once(mock,'listening');
  const probe=createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const port=probe.address().port;await new Promise(r=>probe.close(r));
  const secret='synthetic-backend-test-secret-32-characters';
  const child=spawn(process.execPath,['src/server.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:String(port),ORGANIZER_DATABASE_URL:database.toString(),ORGANIZER_SECRET:secret,IMMICH_URL:`http://127.0.0.1:${mock.address().port}`,VISION_API_KEY:''},stdio:'ignore'});
  const call=(path,method='GET',body,who=owner)=>fetch(`http://127.0.0.1:${port}${path}`,{method,headers:{authorization:`Bearer ${secret}`,'x-organizer-owner':who,'content-type':'application/json'},...(body!==undefined?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});
  try {
    let ready=false;for(let i=0;i<100;i++){try{if((await call('/status')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,50));}assert.ok(ready);
    const connectionId=randomUUID();
    assert.equal((await call('/connect','POST',{key:'synthetic-credential',connectionId})).status,200);
    const duplicate=await (await call('/connect','POST',{key:'different-credential',connectionId:randomUUID()})).json();
    assert.equal(duplicate.connectionId,connectionId);
    const credential=(await sql`SELECT credential FROM owners WHERE id=${owner}`)[0].credential;
    assert.ok(!credential.includes('synthetic'));
    assert.equal((await call('/settings','PUT','{')).status,400);
    assert.equal((await call('/settings','PUT',[])).status,400);
    assert.equal((await call('/status','POST',{})).status,405);
    assert.equal((await call(`/undo/${change}/prepare`)).status,405);
    assert.equal((await call('/assets?offset=1.5')).status,400);
    assert.equal((await call('/runs','POST',{assetIds:[]})).status,400);
    assert.equal((await call('/runs','POST',{limit:1.5})).status,400);
    const run=await(await call('/runs','POST',{limit:999})).json();assert.equal(run.requested,200);
    assert.equal((await sql`SELECT status FROM runs WHERE id=${run.runId}`)[0].status,'queued');
    await sql`INSERT INTO assets(owner,id,checksum,snapshot,provenance) VALUES(${owner},${asset},'hash','{}','{"keep":true}')`;
    assert.equal((await call('/manifest','POST',{entries:[{checksum:'hash',paths:['valid']},{checksum:'bad',paths:[5]}]})).status,400);
    assert.deepEqual((await sql`SELECT provenance FROM assets WHERE owner=${owner}`)[0].provenance,{keep:true},'manifest validation is atomic');
    await sql`INSERT INTO changes(id,owner,asset,before_value,after_value,status) VALUES(${change},${owner},${asset},'{"description":null}','{"description":"after"}','applied')`;
    await call('/connect','POST',{key:'synthetic-other-credential',connectionId:randomUUID()},other);
    assert.equal((await call(`/undo/${change}/prepare`,'POST',{},other)).status,404);
    assert.equal((await call(`/undo/${change}/prepare`,'POST',{})).status,200);
    assert.equal((await sql`SELECT status FROM changes WHERE id=${change}`)[0].status,'undoing');
    description=null;
    assert.equal((await call(`/undo/${change}/prepare`,'POST',{})).status,200,'interrupted write acknowledgment can replay');
    description='manual';
    assert.equal((await call(`/undo/${change}/prepare`,'POST',{})).status,409);
    assert.equal((await call(`/undo/${change}/complete`,'POST',{})).status,409);
    description=null;
    assert.equal((await call(`/undo/${change}/complete`,'POST',{})).status,200);
    assert.equal((await call(`/undo/${change}/prepare`,'POST',{})).status,200,'completed undo is idempotent');
    visibility='locked';
    assert.deepEqual(await(await call('/assets')).json(),[],'cached evidence disappears after locking');
    assert.deepEqual(await(await call('/history')).json(),[],'history cannot disclose a newly locked asset');
    assert.equal((await call(`/assets/${asset}`)).status,404);
  } finally {
    child.kill('SIGKILL');await once(child,'exit');await new Promise(r=>mock.close(r));
    await sql`DELETE FROM changes WHERE owner IN (${owner},${other})`;
    await sql`DELETE FROM assets WHERE owner IN (${owner},${other})`;
    await sql`DELETE FROM runs WHERE owner IN (${owner},${other})`;
    await sql`DELETE FROM owners WHERE id IN (${owner},${other})`;
    await sql.end();
    await administration`DROP SCHEMA ${administration(schema)} CASCADE`;
    await administration.end();
  }
});
